# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    # Coverage settings for the entire project
    project:
      default:
        target: 0% # Target coverage percentage
        threshold: 0% # Allowed decrease rate
        base: auto # Compare with base branch
        if_ci_failed: error # Error on CI failure

    # Coverage settings for patches (newly added code)
    patch:
      default:
        target: 0% # Minimum coverage for new code
        threshold: 0% # Allowed decrease rate for patches
        base: auto

  # Files and directories to exclude from coverage measurement
  ignore:
    - '**/*.config.**'
    - '**/*.spec.**'
    - '**/*.test.**'
    - '**/.next/**'
    - '**/build/**'
    - '**/coverage/**'
    - '**/dist/**'
    - '**/node_modules/**'
    - 'packages/**'

  # Coverage precision settings
  precision: 1 # Decimal places
  round: down # Round down
  range: 0..100 # Coverage range (for color coding)

# Comment settings for pull requests
comment:
  layout: 'reach, diff, flags, files' # Display items
  behavior: default # Default behavior
  require_changes: true # Comment only when coverage changes
  require_base: false # Base branch not required
  require_head: true # HEAD branch required

# Flag management (for monorepo)
flag_management:
  default_rules:
    carryforward: true # Carry forward previous results

  individual_flags:
    # Client-side settings
    - name: client
      paths:
        - apps/client/src/
      target: 100% # Client target
      carryforward: true

    # Server-side settings
    - name: server
      paths:
        - apps/server/src/
      target: 100% # Server target
      carryforward: true

# GitHub integration settings
github_checks:
  annotations: false # Disable code annotations
